name: Gitea CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: Rails checks
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@postgres:5432
      RUBOCOP_CACHE_ROOT: tmp/rubocop
      SOURCE_SYFT_SPDX_SBOM: roastnode-source-${{ github.event.release.tag_name || inputs.release_tag }}.syft.spdx.json
      SOURCE_SYFT_CDX_SBOM: roastnode-source-${{ github.event.release.tag_name || inputs.release_tag }}.syft.cdx.json
      SOURCE_CDX_CDX_SBOM: roastnode-source-${{ github.event.release.tag_name || inputs.release_tag }}.cdx.json
      EXODOS_API_TOKEN: ${{ secrets.EXODOS_API_TOKEN }}
      EXODOS_API_URL: ${{ vars.EXODOS_API_URL }}
      EXODOS_INVENTORYROOT_SYFT_SPDX_ID: ${{ vars.EXODOS_INVENTORYROOT_SYFT_SPDX_ID }}
      EXODOS_INVENTORYROOT_SYFT_CDX_ID: ${{ vars.EXODOS_INVENTORYROOT_SYFT_CDX_ID }}
      EXODOS_INVENTORYROOT_CDX_CDX_ID: ${{ vars.EXODOS_INVENTORYROOT_CDX_CDX_ID }}

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libpq-dev libvips

      - name: Checkout code
        uses: actions/checkout@v6

      - name: set up ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Lint Ruby
        run: bin/rubocop

      - name: Audit gems
        run: bin/bundler-audit

      - name: Audit importmap dependencies
        run: bin/importmap audit

      - name: Scan Rails security
        run: bin/brakeman --quiet --no-pager --exit-on-warn --exit-on-error

      - name: Run Rails tests
        run: bin/rails db:test:prepare test

      - name: Generate container SPDX SBOM Syft
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: ${{ env.SOURCE_SYFT_SPDX_SBOM }}
          artifact-name: ${{ env.SOURCE_SYFT_SPDX_SBOM }}
          upload-artifact-retention: 2

      - name: upload source SPDX sbom to exodos.io
        if: ${{ env.EXODOS_API_TOKEN != '' && env.EXODOS_INVENTORYROOT_SYFT_SPDX_ID != '' }}
        run: |
          set -euo pipefail

          api_url="${EXODOS_API_URL:-https://api.exodos.io}"
          curl -fss -x post "${api_url}/api/v1/boms/inventory/bom/upload" \
            -h "x-api-key: ${EXODOS_API_TOKEN}" \
            -h "accept: application/json" \
            -f "params={\"inventoryroot_id\":\"${EXODOS_INVENTORYROOT_SYFT_SPDX_ID}\",\"tags\":[\"roastnode\",\"source\",\"syft\"}" \
            -f "file=@${SOURCE_SYFT_SPDX_SBOM};type=application/json"

      - name: Generate container CDX SBOM Syft
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          output-file: ${{ env.SOURCE_SYFT_CDX_SBOM }}
          artifact-name: ${{ env.SOURCE_SYFT_CDX_SBOM }}
          upload-artifact-retention: 2

      - name: upload source CycloneDX sbom to exodos.io
        if: ${{ env.EXODOS_API_TOKEN != '' && env.EXODOS_INVENTORYROOT_SYFT_CDX_ID != '' }}
        run: |
          set -euo pipefail

          api_url="${EXODOS_API_URL:-https://api.exodos.io}"
          curl -fss -x post "${api_url}/api/v1/boms/inventory/bom/upload" \
            -h "x-api-key: ${EXODOS_API_TOKEN}" \
            -h "accept: application/json" \
            -f "params={\"inventoryroot_id\":\"${EXODOS_INVENTORYROOT_SYFT_CDX_ID}\",\"tags\":[\"roastnode\",\"source\",\"syft\"}" \
            -f "file=@${SOURCE_SYFT_CDX_SBOM};type=application/json"

      # Generate SBOM via cdxgen
      - name: Download cdxgen Open Source Binary
        run: |
          mkdir -p $HOME/.local/bin
          curl -sSfL https://github.com/CycloneDX/cdxgen/releases/latest/download/cdxgen-linux-amd64 -o $HOME/.local/bin/cdxgen
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Generate SBOM via cdxgen binary
        run: cdxgen -o ${SOURCE_CDX_CDX_SBOM}

      - name: upload container sbom to exodos.io
        if: ${{ env.EXODOS_API_URL != '' && env.EXODOS_INVENTORYROOT_CDX_CDX_ID != '' }}
        run: |
          set -euo pipefail

          api_url="${EXODOS_API_URL:-https://api.exodos.io}"
          curl -fss -x post "${api_url}/api/v1/boms/inventory/bom/upload" \
            -h "x-api-key: ${EXODOS_API_TOKEN}" \
            -h "accept: application/json" \
            -f "params={\"inventoryroot_id\":\"${EXODOS_INVENTORYROOT_CDX_CDX_ID}\",\"tags\":[\"roastnode\",\"source\",\"cdxgen\"}" \
            -f "file=@${SOURCE_CDX_CDX_SBOM};type=application/json"

